# Generated by Django 5.0.6 on 2024-07-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_contact_note_reminder_task_event_calendar_agenda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
