# Generated by Django 5.0.6 on 2024-07-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_agenda_calendar_remove_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeat',
            field=models.CharField(choices=[('NR', 'Does not repeat'), ('DA', 'Daily'), ('WE', 'Weekly'), ('MO', 'Monthly'), ('YE', 'Yearly')], default='NR', max_length=2),
        ),
    ]
