# Generated by Django 5.0.6 on 2024-07-21 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_event_repeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='notes',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
