# Generated by Django 5.0.6 on 2024-07-21 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_remove_agenda_notes_delete_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='reminders',
        ),
        migrations.RemoveField(
            model_name='event',
            name='reminders',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
