# Generated by Django 5.0.6 on 2024-07-21 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_remove_agenda_reminders_remove_event_reminders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='tasks',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
