# Generated by Django 4.2.5 on 2023-11-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaluser',
            name='role',
            field=models.CharField(choices=[('NONE', 'None'), ('DOCTOR', 'Doctor'), ('ADMINISTRATOR', 'Administrator'), ('RECEPTIONIST', 'Receptionist')], max_length=50),
        ),
    ]
