# Generated by Django 4.2.5 on 2023-11-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_last_patient_paterno_patient_materno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first',
            new_name='name',
        ),
    ]
