# Generated by Django 4.2.5 on 2023-11-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_first_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('O', 'OTHER'), ('M', 'MALE'), ('F', 'FEMALE')], default='O', max_length=1),
        ),
    ]
