# Generated by Django 4.2.5 on 2023-11-13 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='has_turns', to='core.patient'),
            preserve_default=False,
        ),
    ]
