# Generated by Django 4.2.5 on 2023-11-13 06:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_turn_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='emited',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='turn',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='has_turns', to='core.patient'),
        ),
    ]
