# Generated by Django 4.2.5 on 2023-11-13 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_turn_emited_alter_turn_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
        ),
    ]
