# Generated by Django 4.2.5 on 2023-11-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_turn_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('O', 'Indefinido'), ('M', 'Masculino'), ('F', 'Femenino')], default='O', max_length=1),
        ),
    ]
