# Generated by Django 4.2.5 on 2023-11-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalunit',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalunit',
            name='priority',
            field=models.IntegerField(choices=[('0', 'Alto'), ('1', 'Medio'), ('2', 'Bajo')], default='2'),
        ),
    ]
