# Generated by Django 4.2.5 on 2023-11-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_medicalunit_name_medicalunit_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalunit',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Alto'), (1, 'Medio'), (2, 'Bajo')], default=2),
        ),
    ]
